name: "Build and Publish"
on:
  repository_dispatch:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write
  discussions: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build

      - name: Find correct JAR
        id: findjar
        run: |
          output="$(find build/libs/ ! -name "*-dev.jar" ! -name "*-sources.jar" -type f -printf "%f\n")"
          echo "::set-output name=jarname::$output"

      - name: Make a GH Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: build/libs/${{ steps.findjar.outputs.jarname }}

      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project_id: ${{ secrets.MODRINTH_PROJECT_ID }}
          file_path: build/libs/${{ steps.findjar.outputs.jarname }}
          name: Release ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}
          game_versions: 1.19.4,1.20,1.20.1
          release_type: release
          loaders: fabric
          featured: true